# base16 scheme generated from the current Omarchy theme. The theme-set hook
# hands it to tinty (base16-omarchy); WezTerm loads it directly.
system: "base16"
scheme: "Omarchy"
name: "Omarchy"
author: "omarchy theme set"
variant: "{{ mode }}"
base00: "{{ background }}"
base01: "{{ mix background foreground 8% }}"
base02: "{{ selection_background }}"
base03: "{{ muted }}"
base04: "{{ light_foreground }}"
base05: "{{ foreground }}"
base06: "{{ bright_foreground }}"
base07: "{{ bright_foreground }}"
base08: "{{ red }}"
base09: "{{ orange }}"
base0A: "{{ yellow }}"
base0B: "{{ green }}"
base0C: "{{ cyan }}"
base0D: "{{ blue }}"
base0E: "{{ magenta }}"
base0F: "{{ accent }}"
